const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getState: () => ipcRenderer.invoke('get-state'),
  saveNote: (gameId, text) => ipcRenderer.invoke('save-note', gameId, text),
  saveReminders: (r) => ipcRenderer.invoke('save-reminders', r),
  setGame: (gameId) => ipcRenderer.invoke('set-game', gameId),
  openUrl: (url) => ipcRenderer.invoke('open-url', url),
  setCompact: (on) => ipcRenderer.invoke('set-compact', on),
  openWeb: () => ipcRenderer.invoke('open-web'),
  openWebExternal: () => ipcRenderer.invoke('open-web-external'),
  captureScore: () => ipcRenderer.invoke('capture-score'),
  fps: () => ipcRenderer.invoke('fps'),
  fpsAdmin: () => ipcRenderer.invoke('fps-admin'),
  openUpdate: (url) => ipcRenderer.invoke('open-update', url),
  onToast: (cb) => ipcRenderer.on('toast', (_e, t) => cb(t)),
  onUpdate: (cb) => ipcRenderer.on('update', (_e, u) => cb(u)),
  rateSession: (start, rating, note) => ipcRenderer.invoke('rate-session', start, rating, note),
  ignoreGame: () => ipcRenderer.invoke('ignore-game'),
  quit: () => ipcRenderer.invoke('quit'),
  cover: (game) => ipcRenderer.invoke('cover', game),
  setSetting: (key, value) => ipcRenderer.invoke('set-setting', key, value),
  snap: (corner) => ipcRenderer.invoke('snap', corner),
  getAutostart: () => ipcRenderer.invoke('get-autostart'),
  setAutostart: (on) => ipcRenderer.invoke('set-autostart', on),
  checkUpdate: () => ipcRenderer.invoke('check-update'),
  onCs2: (cb) => ipcRenderer.on('cs2', (_e, s) => cb(s)),
  onLive: (cb) => ipcRenderer.on('live', (_e, c) => cb(c)),
  onCs2Status: (cb) => ipcRenderer.on('cs2-status', (_e, s) => cb(s)),
  onCs2Match: (cb) => ipcRenderer.on('cs2-match', (_e, m) => cb(m)),
  onSessionSummary: (cb) => ipcRenderer.on('session-summary', (_e, s) => cb(s)),
  hide: () => ipcRenderer.invoke('hide'),
  show: () => ipcRenderer.invoke('show'),
  systemStats: () => ipcRenderer.invoke('system-stats'),
  onGameChanged: (cb) => ipcRenderer.on('game-changed', (_e, g) => cb(g)),
  onMode: (cb) => ipcRenderer.on('mode', (_e, m) => cb(m)),
  onSettings: (cb) => ipcRenderer.on('settings', (_e, s) => cb(s)),
  // Evolução
  evolution: (game, days) => ipcRenderer.invoke('evolution', game, days),
  evoSync: () => ipcRenderer.invoke('evo-sync'),
  setGoals: (list) => ipcRenderer.invoke('set-goals', list),
  askClaude: (game, days) => ipcRenderer.invoke('ask-claude', game, days),
  onHistory: (cb) => ipcRenderer.on('history-changed', () => cb()),
  // HUD
  onHud: (cb) => ipcRenderer.on('hud', (_e, d) => cb(d)),
  hudSize: (w, h) => ipcRenderer.invoke('hud-size', w, h),
  setTimers: (list) => ipcRenderer.invoke('set-timers', list),
  // Turbo
  turboProcs: () => ipcRenderer.invoke('turbo-procs'),
  turboClose: (name, force) => ipcRenderer.invoke('turbo-close', name, force),
  onTurboDrop: (cb) => ipcRenderer.on('turbo-drop', (_e, d) => cb(d)),
  onTurboPower: (cb) => ipcRenderer.on('turbo-power', (_e, s) => cb(s)),
  // Clipes
  saveClip: () => ipcRenderer.invoke('save-clip'),
  clips: () => ipcRenderer.invoke('clips'),
  openClip: (file) => ipcRenderer.invoke('open-clip', file),
  openClipsFolder: () => ipcRenderer.invoke('open-clips-folder'),
  onClips: (cb) => ipcRenderer.on('clips', (_e, c) => cb(c)),
  onRec: (cb) => ipcRenderer.on('rec', (_e, m) => cb(m)),
  recStatus: (st) => ipcRenderer.invoke('rec-status', st),
  recFile: (buf, ms, meta) => ipcRenderer.invoke('rec-file', buf, ms, meta)
});
